Address = "0x502aecfe253e6aa0e8d2a06e12438ffed0fe16a0"
RPC = "https://rpc.bscscanmev.io"
Description = "Your Gateway to the BNB Smart Chain Network. BscScan is the leading BSC Block Chain Explorer and one of the earliest independent project built and developed for the BNB Smart Chain"